# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(939, 682)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.MethodBox = QtWidgets.QComboBox(self.centralwidget)
        self.MethodBox.setObjectName("MethodBox")
        self.MethodBox.addItem("")
        self.MethodBox.addItem("")
        self.MethodBox.addItem("")
        self.MethodBox.addItem("")
        self.MethodBox.addItem("")
        self.MethodBox.addItem("")
        self.MethodBox.addItem("")
        self.gridLayout.addWidget(self.MethodBox, 3, 1, 1, 1)
        self.ExtractEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ExtractEdit.setObjectName("ExtractEdit")
        self.gridLayout.addWidget(self.ExtractEdit, 4, 3, 1, 1)
        self.GrindEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.GrindEdit.setObjectName("GrindEdit")
        self.gridLayout.addWidget(self.GrindEdit, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.QualLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.QualLabel.setFont(font)
        self.QualLabel.setObjectName("QualLabel")
        self.gridLayout.addWidget(self.QualLabel, 8, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.FinishQualSlide = QtWidgets.QSlider(self.centralwidget)
        self.FinishQualSlide.setMaximum(10)
        self.FinishQualSlide.setOrientation(QtCore.Qt.Horizontal)
        self.FinishQualSlide.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.FinishQualSlide.setTickInterval(1)
        self.FinishQualSlide.setObjectName("FinishQualSlide")
        self.gridLayout.addWidget(self.FinishQualSlide, 8, 5, 1, 1)
        self.BodyEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyEdit.sizePolicy().hasHeightForWidth())
        self.BodyEdit.setSizePolicy(sizePolicy)
        self.BodyEdit.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(9)
        self.BodyEdit.setFont(font)
        self.BodyEdit.setObjectName("BodyEdit")
        self.gridLayout.addWidget(self.BodyEdit, 9, 4, 1, 1)
        self.SweetLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.SweetLabel.setFont(font)
        self.SweetLabel.setObjectName("SweetLabel")
        self.gridLayout.addWidget(self.SweetLabel, 6, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.AcidQuantSlide = QtWidgets.QSlider(self.centralwidget)
        self.AcidQuantSlide.setMaximum(10)
        self.AcidQuantSlide.setOrientation(QtCore.Qt.Horizontal)
        self.AcidQuantSlide.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.AcidQuantSlide.setTickInterval(1)
        self.AcidQuantSlide.setObjectName("AcidQuantSlide")
        self.gridLayout.addWidget(self.AcidQuantSlide, 7, 2, 1, 1)
        self.AromaQualSlide = QtWidgets.QSlider(self.centralwidget)
        self.AromaQualSlide.setMaximum(10)
        self.AromaQualSlide.setOrientation(QtCore.Qt.Horizontal)
        self.AromaQualSlide.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.AromaQualSlide.setTickInterval(1)
        self.AromaQualSlide.setObjectName("AromaQualSlide")
        self.gridLayout.addWidget(self.AromaQualSlide, 8, 1, 1, 1)
        self.BodyQuantSlide = QtWidgets.QSlider(self.centralwidget)
        self.BodyQuantSlide.setMaximum(10)
        self.BodyQuantSlide.setOrientation(QtCore.Qt.Horizontal)
        self.BodyQuantSlide.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.BodyQuantSlide.setTickInterval(1)
        self.BodyQuantSlide.setObjectName("BodyQuantSlide")
        self.gridLayout.addWidget(self.BodyQuantSlide, 7, 4, 1, 1)
        self.AromaQuantSlide = QtWidgets.QSlider(self.centralwidget)
        self.AromaQuantSlide.setAutoFillBackground(False)
        self.AromaQuantSlide.setMaximum(10)
        self.AromaQuantSlide.setSingleStep(1)
        self.AromaQuantSlide.setOrientation(QtCore.Qt.Horizontal)
        self.AromaQuantSlide.setInvertedAppearance(False)
        self.AromaQuantSlide.setInvertedControls(False)
        self.AromaQuantSlide.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.AromaQuantSlide.setObjectName("AromaQuantSlide")
        self.gridLayout.addWidget(self.AromaQuantSlide, 7, 1, 1, 1)
        self.AromaLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.AromaLabel.setFont(font)
        self.AromaLabel.setObjectName("AromaLabel")
        self.gridLayout.addWidget(self.AromaLabel, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.OveralLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.OveralLabel.setFont(font)
        self.OveralLabel.setObjectName("OveralLabel")
        self.gridLayout.addWidget(self.OveralLabel, 12, 0, 3, 1, QtCore.Qt.AlignHCenter)
        self.SweetEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweetEdit.sizePolicy().hasHeightForWidth())
        self.SweetEdit.setSizePolicy(sizePolicy)
        self.SweetEdit.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(9)
        self.SweetEdit.setFont(font)
        self.SweetEdit.setObjectName("SweetEdit")
        self.gridLayout.addWidget(self.SweetEdit, 9, 3, 1, 1)
        self.OverallEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OverallEdit.sizePolicy().hasHeightForWidth())
        self.OverallEdit.setSizePolicy(sizePolicy)
        self.OverallEdit.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(9)
        self.OverallEdit.setFont(font)
        self.OverallEdit.setObjectName("OverallEdit")
        self.gridLayout.addWidget(self.OverallEdit, 12, 1, 3, 4)
        self.AcidEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AcidEdit.sizePolicy().hasHeightForWidth())
        self.AcidEdit.setSizePolicy(sizePolicy)
        self.AcidEdit.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(9)
        self.AcidEdit.setFont(font)
        self.AcidEdit.setObjectName("AcidEdit")
        self.gridLayout.addWidget(self.AcidEdit, 9, 2, 1, 1)
        self.QuantLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.QuantLabel.setFont(font)
        self.QuantLabel.setObjectName("QuantLabel")
        self.gridLayout.addWidget(self.QuantLabel, 7, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.NotesLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.NotesLabel.setFont(font)
        self.NotesLabel.setObjectName("NotesLabel")
        self.gridLayout.addWidget(self.NotesLabel, 9, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.SweetQualSlide = QtWidgets.QSlider(self.centralwidget)
        self.SweetQualSlide.setMaximum(10)
        self.SweetQualSlide.setOrientation(QtCore.Qt.Horizontal)
        self.SweetQualSlide.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SweetQualSlide.setTickInterval(1)
        self.SweetQualSlide.setObjectName("SweetQualSlide")
        self.gridLayout.addWidget(self.SweetQualSlide, 8, 3, 1, 1)
        self.AromaEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AromaEdit.sizePolicy().hasHeightForWidth())
        self.AromaEdit.setSizePolicy(sizePolicy)
        self.AromaEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.AromaEdit.setMaximumSize(QtCore.QSize(10000000, 900))
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(9)
        self.AromaEdit.setFont(font)
        self.AromaEdit.setObjectName("AromaEdit")
        self.gridLayout.addWidget(self.AromaEdit, 9, 1, 1, 1)
        self.BodyLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.BodyLabel.setFont(font)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout.addWidget(self.BodyLabel, 6, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.AcidLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.AcidLabel.setFont(font)
        self.AcidLabel.setObjectName("AcidLabel")
        self.gridLayout.addWidget(self.AcidLabel, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.AcidQualSlide = QtWidgets.QSlider(self.centralwidget)
        self.AcidQualSlide.setMaximum(10)
        self.AcidQualSlide.setOrientation(QtCore.Qt.Horizontal)
        self.AcidQualSlide.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.AcidQualSlide.setTickInterval(1)
        self.AcidQualSlide.setObjectName("AcidQualSlide")
        self.gridLayout.addWidget(self.AcidQualSlide, 8, 2, 1, 1)
        self.FinishEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FinishEdit.sizePolicy().hasHeightForWidth())
        self.FinishEdit.setSizePolicy(sizePolicy)
        self.FinishEdit.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(9)
        self.FinishEdit.setFont(font)
        self.FinishEdit.setObjectName("FinishEdit")
        self.gridLayout.addWidget(self.FinishEdit, 9, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.SweetQuantSlide = QtWidgets.QSlider(self.centralwidget)
        self.SweetQuantSlide.setMaximum(10)
        self.SweetQuantSlide.setOrientation(QtCore.Qt.Horizontal)
        self.SweetQuantSlide.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SweetQuantSlide.setTickInterval(1)
        self.SweetQuantSlide.setObjectName("SweetQuantSlide")
        self.gridLayout.addWidget(self.SweetQuantSlide, 7, 3, 1, 1)
        self.BodyQualSlide = QtWidgets.QSlider(self.centralwidget)
        self.BodyQualSlide.setMaximum(10)
        self.BodyQualSlide.setOrientation(QtCore.Qt.Horizontal)
        self.BodyQualSlide.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.BodyQualSlide.setTickInterval(1)
        self.BodyQualSlide.setObjectName("BodyQualSlide")
        self.gridLayout.addWidget(self.BodyQualSlide, 8, 4, 1, 1)
        self.FinishLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.FinishLabel.setFont(font)
        self.FinishLabel.setObjectName("FinishLabel")
        self.gridLayout.addWidget(self.FinishLabel, 6, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.FinishQuantSlide = QtWidgets.QSlider(self.centralwidget)
        self.FinishQuantSlide.setMaximum(10)
        self.FinishQuantSlide.setOrientation(QtCore.Qt.Horizontal)
        self.FinishQuantSlide.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.FinishQuantSlide.setTickInterval(1)
        self.FinishQuantSlide.setObjectName("FinishQuantSlide")
        self.gridLayout.addWidget(self.FinishQuantSlide, 7, 5, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.FlavoutEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FlavoutEdit.sizePolicy().hasHeightForWidth())
        self.FlavoutEdit.setSizePolicy(sizePolicy)
        self.FlavoutEdit.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(9)
        self.FlavoutEdit.setFont(font)
        self.FlavoutEdit.setObjectName("FlavoutEdit")
        self.gridLayout.addWidget(self.FlavoutEdit, 11, 1, 1, 5)
        self.FlavourLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.FlavourLabel.setFont(font)
        self.FlavourLabel.setObjectName("FlavourLabel")
        self.gridLayout.addWidget(self.FlavourLabel, 11, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setMinimumSize(QtCore.QSize(0, 10))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 6)
        self.ScoreBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScoreBox.sizePolicy().hasHeightForWidth())
        self.ScoreBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(9)
        self.ScoreBox.setFont(font)
        self.ScoreBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ScoreBox.setObjectName("ScoreBox")
        self.gridLayout.addWidget(self.ScoreBox, 12, 5, 1, 1)
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveButton.sizePolicy().hasHeightForWidth())
        self.SaveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(9)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.gridLayout.addWidget(self.SaveButton, 13, 5, 1, 1)
        self.HistoryButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HistoryButton.sizePolicy().hasHeightForWidth())
        self.HistoryButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(9)
        self.HistoryButton.setFont(font)
        self.HistoryButton.setObjectName("HistoryButton")
        self.gridLayout.addWidget(self.HistoryButton, 14, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.RatioEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RatioEdit.setObjectName("RatioEdit")
        self.gridLayout.addWidget(self.RatioEdit, 3, 3, 1, 1)
        self.AdvView = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.AdvView.setFont(font)
        self.AdvView.setObjectName("AdvView")
        self.gridLayout.addWidget(self.AdvView, 4, 4, 1, 2, QtCore.Qt.AlignHCenter)
        self.BrewDateEdit = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(8)
        self.BrewDateEdit.setFont(font)
        self.BrewDateEdit.setCalendarPopup(True)
        self.BrewDateEdit.setObjectName("BrewDateEdit")
        self.gridLayout.addWidget(self.BrewDateEdit, 3, 5, 1, 1)
        self.BrewDateLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.BrewDateLabel.setFont(font)
        self.BrewDateLabel.setObjectName("BrewDateLabel")
        self.gridLayout.addWidget(self.BrewDateLabel, 3, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.NameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.NameEdit.setObjectName("NameEdit")
        self.gridLayout.addWidget(self.NameEdit, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.RoastEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.RoastEdit.setObjectName("RoastEdit")
        self.gridLayout.addWidget(self.RoastEdit, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.RoastDate = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        self.RoastDate.setFont(font)
        self.RoastDate.setCalendarPopup(True)
        self.RoastDate.setObjectName("RoastDate")
        self.gridLayout.addWidget(self.RoastDate, 2, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 939, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MethodBox.setItemText(0, _translate("MainWindow", "V60"))
        self.MethodBox.setItemText(1, _translate("MainWindow", "AeroPress"))
        self.MethodBox.setItemText(2, _translate("MainWindow", "Espresso"))
        self.MethodBox.setItemText(3, _translate("MainWindow", "French Press"))
        self.MethodBox.setItemText(4, _translate("MainWindow", "Mellita"))
        self.MethodBox.setItemText(5, _translate("MainWindow", "Chemex"))
        self.MethodBox.setItemText(6, _translate("MainWindow", "Moka Pot"))
        self.label_15.setText(_translate("MainWindow", "Extraction \n"
"Time"))
        self.QualLabel.setText(_translate("MainWindow", "Quality"))
        self.SweetLabel.setText(_translate("MainWindow", "Sweetness"))
        self.AromaLabel.setText(_translate("MainWindow", "Aroma"))
        self.OveralLabel.setText(_translate("MainWindow", "Overall/\n"
"OtherNotes"))
        self.QuantLabel.setText(_translate("MainWindow", "Quantity"))
        self.NotesLabel.setText(_translate("MainWindow", "Notes"))
        self.BodyLabel.setText(_translate("MainWindow", "Body"))
        self.AcidLabel.setText(_translate("MainWindow", "Acidity"))
        self.label_13.setText(_translate("MainWindow", "Grind \n"
"Setting"))
        self.FinishLabel.setText(_translate("MainWindow", "Finish"))
        self.label_17.setText(_translate("MainWindow", "Method"))
        self.FlavourLabel.setText(_translate("MainWindow", "Flavour"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.HistoryButton.setText(_translate("MainWindow", "History"))
        self.label_16.setText(_translate("MainWindow", "Ratio"))
        self.AdvView.setText(_translate("MainWindow", "Advanced View"))
        self.BrewDateLabel.setText(_translate("MainWindow", "Brew Date"))
        self.label_8.setText(_translate("MainWindow", "Coffee"))
        self.label_9.setText(_translate("MainWindow", "Roaster"))
        self.label_14.setText(_translate("MainWindow", "Roast Date"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

